battle.net:
    client:
        clientId: a98s92ax3z2gpacag66f2eh252pduce6
        clientSecret: KVfPuCteJQCyUxRVAQkAanmNaUkjrB7w
        accessTokenUri: https://US.battle.net/oauth/token
        userAuthorizationUri: https://US.battle.net/oauth/authorize
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form